### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by maxreig** [DaniGuardiola/telegram-welcome-bot#1]
Buenos dias Dani,

Estaba mirando el repo para poder utilizarlo ya que dispongo de un grupo de Telegram, lo veo muy senzillo pero no me queda claro donde indicas el canal que quieras que se ejecute el bot de bienvenida,

Un saludo y gracias,

**Comment by DaniGuardiola** [comment]
Hola @maxreig!

Pues si ya tienes el bot creado, solo tienes que añadirlo a un grupo. Un saludo!
